# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &office3
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: office3MSP

    # ID to load the MSP definition as
    ID: office3MSP

    MSPDir: ../organizations/peerOrganizations/office3.lithium.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('office3MSP.admin', 'office3MSP.peer', 'office3MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('office3MSP.admin', 'office3MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('office3MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('office3MSP.peer')"

    AnchorPeers:
      # AnchorPeers defines the location of peers which can be used
      # for cross org gossip communication.  Note, this value is only
      # encoded in the genesis block in the Application section context
      - Host: peer0.office3.lithium.com
        Port: 11051
