version: "2"

networks:
  office:

services:
  redis1:
    image: "redis:latest"
    container_name: redis.office1.ccu.com
    command: redis-server --requirepass office1ccu
    ports:
      - "6379:6379"
    networks:
      - office

  redis2:
    image: "redis:latest"
    container_name: redis.office2.ccu.com
    command: redis-server --requirepass office2ccu
    ports:
      - "6380:6379"
    networks:
      - office

  redis3:
    image: "redis:latest"
    container_name: redis.office3.ccu.com
    command: redis-server --requirepass office3ccu
    ports:
      - "6381:6379"
    networks:
      - office
