version: "2"

networks:
  office:

services:
  redis1:
    image: "redis:latest"
    container_name: redis.office1.lithium.com
    command: redis-server --requirepass office1lithium
    ports:
      - "6379:6379"
    networks:
      - office

  redis2:
    image: "redis:latest"
    container_name: redis.office2.lithium.com
    command: redis-server --requirepass office2lithium
    ports:
      - "6380:6379"
    networks:
      - office

  redis3:
    image: "redis:latest"
    container_name: redis.office3.lithium.com
    command: redis-server --requirepass office3lithium
    ports:
      - "6381:6379"
    networks:
      - office
